---
- hosts: all 
  become: yes
  become_user: root 
 
  vars: 
    ansible_sudo_pass: devops
 
  tasks:
   - name: Installing Latest version of Apache
     yum:
       name=httpd
       state=latest
   - name: Copying the demo file
     template: 
       src=/home/devops/index.html 
       dest=/var/www/html
       owner=apache 
       group=apache 
       mode=0644
   - name: (Enable it on System Boot)
     service: 
       name=httpd 
       enabled=yes
