---
- hosts: all
  become: yes
  become_user: devops
  tasks:
  debug:
    msg: "{{ hostvars[inventory_hostname].ansible_distribution }}"
  debug:
    msg: "{{ hostvars[inventory_hostname].ansible_distribution_major_version }}"
  debug:
    msg: "{{ hostvars[inventory_hostname].ansible_distribution_version }}"
